name: Test

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: list files
        run: ls -la
        
      - name: scp
        run: scp -P ${{secrets.PORT}} calc.py ${{secrets.USERNAME}}@${{secrets.HOST}}:/home/alexander/PycharmProjects
