name: Test

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: instal req
        run: pip install -r requirements.txt
        
      - name: compile .exe
        run: pyinstaller --onefile calc.py
        
      - name: update cursor
        run: cd /home/runner/work/calculator/calculator/dist
        
      - name: scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "calc"
          target: "/home/alexander/PycharmProjects"
          
