name: Test

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: list files
        run: ls -la
       
      - name: scp
        uses: borovskiy/calculator@main
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          sourse: "calc.py"
          target: "/home"
          
        
        
        
        
        
        
#         run: scp cacl.py ${{ secrets.USERNAME }}@${{ secrets.HOST }} -p ${{ secrets.PORT }}:/home/alexander/PycharmProjects


# ${{ secrets.USERNAME }}
# ${{ secrets.HOST }}
# ${{ secrets.PORT }}
