name: Test

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
       
      - name: scp
        run: scp cacl.py ${{ env.USERNAME }}@${{ env.HOST }} -p ${{ env.PORT }}:/home/alexander/PycharmProjects


