name: Test

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: checkout
       uses: actions/checkout@v1
     - name: copy file
       run: echo "${{secrets.PORTS}}"
#        uses: ./
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          password: ${{ secrets.PASSWORD }}
#          port: ${{ secrets.PORT }}
#          source: "calc.py"
#          target: "test"
         
