name: Test

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: instal req
        run: pip install requirements.txt
      - name: compile .exe
        run: pyinstaller --onfile calc.py
      
      - name: copy file in server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "/dist/cacl"
          target: "/home/alexander/PycharmProjects"
          
