name: Test

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: list files
        run: ls -la
       
      - name: scp
        run: pip install -r requirements.txt
#         run: scp cacl.py ${{ secrets.USERNAME }}@${{ secrets.HOST }} -p ${{ secrets.PORT }}:/home/alexander/PycharmProjects


