name: Test

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: instal req
        run: pip install -r requirements.txt
        
      - name: compile .exe
        run: pyinstaller --onefile calc.py
      
      - name: dir
        run: cd dist/ 
      - name: olist dir
        run: ls -la
#         uses: appleboy/scp-action@master
# #         with:
# #           host: ${{ secrets.HOST }}
# #           username: ${{ secrets.USERNAME }}
# #           password: ${{ secrets.PASSWORD }}
# #           port: ${{ secrets.PORT }}
# #           source: "/dist"
# #           target: "/home/alexander/PycharmProjects"
          
